
const posts = [
    "hola plis como saben yo tambien estoy en busca de un juego que cuando era muy pequeñita lo juegue pero no recuerdo su nombre, recuerdo que el juego cuando tu entrabas la imagen que te ponian cuando el juego se estaba cargando era de una chica y un chico exploradores aventureros, y luego cuando ya cuando entrabas el juego era como que los personajes eran bien pequeños y es como que tenias que explorar para poder desbloquear mas islitas cada una distintas y tenias cada vez mas personajes era algo asi como una isla pirata y la musica tambien era como de piratas... primero empezaban con los personajes del chico y la chica y a medida que ibas avanzando de nivel y tenias mas dinero o mas rubies no recuerdon muy bien esa parte y te daban personajes nuevos, nose si es un juego que se pueda jugar o que ya venga instalado en la tablet porque nose muy bien si eso me lo instalaron en la tablet o ya venia, plisssss les pido si alguien sabe como se llama avisenmeee que estoy desesperada por volverlo a jugar...",
    "Hola, busco un juego de un explorador que cae en un avión y creo que se metía a una pirámide era muy entretenido, si sabes algo me cuentas...creo que si te demorabas salía un fantasma persiguiendote",
    "Hola busco un juego de una abeja que entra a una piramide y dispara con su colita, y una de sus misiones era contra una araña grande que aparece adentro de la piramide",
    "Hola alguien sabe como se llama el juego en donde una niña es capturada por un monstruo en una feria, y el niño de traje azul con un casco va a salvarla, ellos están primero en un cine. El niño lanza pelotas o balones dependiendo del daño que le hagan",
    "HOLA BUSCO UN JUEGO DE UN SOLDADO, que se podia subir a tanques habian tanques grandes y chicos, era bien basico eso si que si te daban al tanque salia humo y tenias que salir rapido, y despues esplotaba",
    "hola me gustaría que me ayudaran a encontrar el título de un juego para la NES, se trataba de un agente que disparaba a sus enemigos con una pistola, parecia un juego de ganster, el personaje se podía meter a las coladeras de la ciudad y en el drenaje había mas misiones en donde caía acido de color azul del techo del drenaje, espero que me ayuden a encontrar el titulo de dicho video juego gracias comunidad gamer saludos",
    "Busco un juego de una casa embrujada, tenias que agarrar dulces y llaves para abrir puertas, y tambien podias cambiar los personajes a payaso policia etc",
    "Esta es la descripcion que me dan dos amigos sobre su juego añorado de antaño, juego de PS2 (hablamos entre año 2000 a 2005) 3D, Multiples enemigos en pantalla, uno de los personajes (o el personaje pues no recuerdan si eran varios) era una bruja, en algun punto la bruja gritaba (quizas lo mas importante para ellos): 'I AM REBORN', y esa es toda la informacion que he logrado recopilar al respecto. Gracias por la ayuda :)",
    "Estoy buscando un juego que es de plataformas y estrategia. Trata de un cubo parecido a una cajita de lavadora. Tiene un agujero y de ese agujero sale una especie como taladro que puede romper otros cubos como de piedra. el juego se desarrolla como si estuvieran en un laberinto bajo la tierra y la estrategia es que al romper estos cubos puede llegar a la salida. este cubito es de color blanco. agradezco la ayuda",
    "Hola! Busco un juego de pc, época alrededor del 2000, fantasía medieval, vista como isométrica pero se podía girar si no me equivoco como una brújula, recuerdo que había varios personajes con diferentes habilidades que se podía seleccionar y subir de nivel y entre ellos había un arquero. Recuerdo que iban juntos por el escenario pero tu sólo podías manejar uno a la vez. No es tipo baldur gate y esos que son rol puro, éste era como un poco más de acción a golpe de ratón. Creo que recordar que tenias que derrotar enemigos (muchos de ellos magos) que estaban delante de cofres de distintos niveles. Se que no doy muchas pistas pero no recuerdo mucho más Gracias",
    "Hola estoy buscando un juego de los 80 que se trata de un hombre que se monta en una especie de avestruz y va recogiendo huevos, y además tiene que matar a una especie de dragones con una lanza que lleva, un juego muy divertido si me puedes ayudar te estaría muy agradecido muchas gracias y un saludo ",
    "Estoy buscando un título de juego de video de los años 90, en donde un hombrecito volador tenia que pasar varios niveles, el que mas recuerdo es donde dentro de una pirámide el jefe era una avispa",
    "Busco un juego que solía salir en los video juegos (maquinitas como muchos los conocemos). Trata sobre algo parecido a unos pollitos alienigenas que vas disparando, cuando se acerca el enemigo se ocultan debajo de la tierra. Si no salen a tiempo mueren!, Me ayudan a saber cómo se llama",
    "Buen día! Busco un juego que era de la NES. Lo que recuerdo era que el personaje era como una especie de explorador, ademas traia una mochila. Al saltar de un sitio alto podia usar unas hélices de helicóptero (qie estaban dentro de la mochila) para descender lento. También tenia un gancho con el qie podias escalar. Recuerdo que el juego se desarrollaba en una selva o jungla y también mostraban un mapa al finalizar el nivel. Saludos!",
    "HOLA ¿QUE TAL? NECESITO POR FAVOR QUE ALGUIEN ME DIGA POR FAVOR, EL NOMBRE DE UN JUEGO QUE VENIA EN UN DISCO PARA LA COMPUTADORA Y SE TRATABA DE UN COMO MARCIANO AZUL, Y APRENDÍAS INGLES Y SE HACIA MISIONES, POR EJEMPLO EN UNA COCINA APRETABAS TODAS LAS COSAS QUE SE ENCONTRABAN Y TE LO DECIAN EN INGLES Y EN ESPAÑOL, Y TENIAS QUE ENCONTRAR LAS PALABRAS DE CADA HABITACION PARA QUE AL FINAL TE VENIA UNA TIPO ORACIÓN Y LAS TENIAS QUE A COMPLETAR CON ESAS PALABRAS. POR FAVOR EN SERIO ME URGE SABER EL NOMBRE LO JUGABA DE NIÑA Y LLEVO AÑOS BUSCANDO MI DISCO E INTENTANDO SABERLO. POR FAVOR",
    "Hola quiero saber como se llamaba un juego que era de un niño gordito, y los niveles eran de comida, y cada vez que llegabas al final para ganarlo tenias que derrotar a un cerdo con la boca ancha que arrojaba cerditos por la boca",
    "Burnos días A ver si alguien puedr ayudarme. Busco el nombre de un video juego del nintendo 1985 (ese modelo) no se de q año es el juego. El personaje iba entrando en habitaciones q llevaban A otras habitaciones, eran cuartos en olan castillo, como de la epoca medieval. Y los cuartos tenian trampas, y pruebas x superar. Los poderes q el personaje cogia estaban en forma de posiones maguca es decir, liquidos de colores dentro de tubis de laboratorio, y el traje del personaje era como una bata larga y llevaba un sombrero grande. Como de mago medieval. Nunca supe mas de ese juego y es como una espina xq jamas lo pase ni recyerdo el nombre si alguien le suena y me puede orientar x el nombre se lo agradezco Buenos dias.",
    "Hola busco un juego de family, el protagonista era un niño que disparaba pelotas para vencer a sus enemigos, era una aventura donde avanzabas a través de niveles laterales, recuerdo que entre sus jefes estaba un tigre que ocupaba la mitad de la pantalla, asi como la cabeza de un indio gigante, no recuerdo nada más espero me puedan ayudar",
    "estoy buscando un juego de un dinosaurio, que comenzando llega en una canasta por un rió o una cascada y lo crían unos animalitos como unas volitas con una cola atrás, y tiene que ir buscando llaves para pasar por puertas",
    "como se llama el juego en donde empiezas en un lugar con lava y tienes que ir subiendo por unos ascensores, era tipo rol en 3ra persona, lo juge mas o menos en el 2004 o 2005 para que sepas que es viejito :3",
    "hoolaaaaaaaaaaaaaa busco un juego, me se el nombre pero a un asi no lo puedo encontrar, el juego se llama 'Challenge' este era para celular sony ericsson, en si el juego era tetris con mucho mas dinamismo, era otro rollo se divertia una con los animaciones originales que traia los juegos de java pero a un asi no lo encuentro, si alguien se llega leer este comentario por favor buscalo para ver si tu perspectiva de google te lo da.. si lo hallas contestame es muy diertido. el juego solo asi se llama 'Challenge' no aceptes otros. el juegoo venia en un cell sony ericsson w910i",
    "Buenas busco un juego que lo jugaba alrededor de 2007-2008-2009 que era de plataformas y a la vez con armas, los enemigos tenian un casco negro y rojo y tu personaje negro y verde, habia varias pruebas y varias armas de las cuales habia una espada laser, era un juego entretenido y lo jugaba en la biblioteca de mi colegio, hace mucho que no se nada de el y se me olvido el nombre, otra cosa que llego a recordar es que al final de cada prueba habia un boss. Gracias por leerme",
    "Busco un juego donde yo controlo a muchos monstruos con una mano, y tengo que encontrar un caballero y destruir el pozo que sería la vida de ellos, Ejemplo de los monstruos: Ponía a estudiar a los hechiceros",
    "Busco aneladamente un juguetue k era tipo zorrito, teniai sus manitos juntas komo para agarrar hojas, yo soy del 95 y hasta ASE poko vi ese mono pero en grandeeee, es hermoso super tierno, es tipo zorrito blanko y negro y su varita muy tierna",
    "Hola ¿Cómo están?. Estiy buscando un par de juegos que jugaba de pequeña, tengo muy pocos recuerdos de ellos y tampoco sé las plataformas ni nada, solo puedo decirles que hoy dia tengo 16 años, asi no han de ser demasiado viejos. El primer juego era un juego era un juego de plataformas, en el que tu eras una 'princesa ardilla' o algo asi, estabas como bajo la tierra y te movias por túneles o algo así, no sé si buscabas oro u otra cosa, pero era algo así. El segundo juego era uno de esos juegos en los que debes salir de un lugar donde estás encerrado. Estabas en un tren, tengo el recuerdo de que había muchísimo color verde no lo tengo muy claro, pero era un tren fantasma o algo por el estilo. Espero puedan ayudarme a pesar de lo poco detalladas que son mis peticiones, muchas gracias.",
    "Hola. Estoy buscando 2 nombres de juegos para pc mas o menos entre el año 1999 y 2000. El primero es en 3D en tercera persona, el personaje de color naranja es como un zorro (no es el crash bandicot) va corriendo por una playa donde unos extraterrestres han invadido la ciudad. El nombre del juego contenia la palabra Star pero mas de eso no recuerdo. El segundo juego se trataba de una carrera de avionetas en 3D tambíen que volaban entre acantilados sobre el agua a mucha velocidad. Gracias!",
    "Buenos días, El juego que me gustaría encontrar venía para psx. Era de acción. Creo que era estilo anime. El primer escenario era nocturno. Si mal no recuerdo ibamos sobre un crucero. Me parece que se podían escoger 2 personajes para jugar una era una mujer rubia. Usábamos pistolas. Vestían de forma elegante. Y de pronto aparecían muchos enemigos trajeados que habia que exterminar. No recuerdo más porque no llegué a avanzar más jeje. PD: no es trap gunner :(",
    "Hola necesito tu ayuda, he visto que es muy amable y ayuda a encontrar juegos. Llevo muucho tiempo intentando recordar el nombre de un juego al que jugaba en un mac PC. Era de ordenador, antiguo (sobre el 2000- 2006 igual no lo sabría decir). Tu eras un personaje amarillo naranjoso con unas extremidades poco marcadas (como si fueras un Kirby amarillo pero más feo). El personaje levaba una mochila verde y tenía que ir recogiendo gemas. Creo recordar que llevaba una pala en la mano. El jueo era de diferentes pantallas, ibas avanzando poco a poco. En cada pantalla había dos o tres plataformas horizontales (tierra por abajo y hierba verde por encima). El juego se parece al Spelunky de paisaje pero eran niveles verticales, creo que no estaban bajo tierra (era todo de un color verde con agua azul en algunas pantallas) y el personaje no era un hombre, era como una patat extraña de plastelina amarilla. Espero que pueda ayudarme a recordar el nombre! Perdone por hacerle perder su tiempo",
    "ola amigo, entre a tu pagina y deje un comentario, pero no pude visualizarlo no se si se puso o no, solo quiero saber de un juego que jugaba hacer tiempo, mas o menos por los años 90 se trata de un juego de aviones lo unico que recuerdo es que se enfrentaba en a un tren y conforme  hibas pasando misiones te enfrentabas a un ferrocarril, ehh iggual hibas agarrando armas tmb la nave se le ponian dos bolas como protectores, es lo unico que recuerdo. saludos",
    "Buen día. Quisiera saber si conoce un juego que fue para palm, de un caviernicola, tratando de avanzar por varios niveles, se desarrolla en el hielo y hay varios trucos que había que descifrar. Saludos",
    "video juego viejisimo de maquina grande. tremendo juego de aventura q nunca mas lo pude encontrar. se trata de 2 magos o duendes q tiran como vaias bolas a la ves y los ecenarioa son plataformas los enemigos q me acuerdo algunos de ellos aparecen cañones q disparan y van saltando de plataformas en plataformas. un ecenario me acuerdo q era de hielo",
    "Hola cuando era niña mas o menos del 91 creo jugue pacman en un atari. El pacman no es como estos no, traía niveles y tenia bombitas salían las frutitas que ganabas en cada nivel lo volvi a encontrar en el 2006 pero no puse atencion, yo quiero ese me recuerda a esa etapa tan bonita de mi vida por favor ayudenme",
    "alguien me puede ayudar con un juego en el que salia un muchacho en un cementerio con una gorra roja, que tenia que agarrar unas cosas, y despues irse por una puerta que decia exit",
    "Como es el nombre del juego de la consola family, en el q podes elegir a un niño un raton un hombre de piedra y un dragon... pasan cada uno su nivel q le corresponden y a partir del nivel 5 en adelante se pueden elegir intercambiando los personajes  ...es de aventura tan bueno como aventura island...2D ",
    "podrian decirme el nombre de este magnifico juego es uno parecido a robocop es algo asi como un robot q lleva consigo una pequeña nave q lo sigue arriba de su cabeza a unos metros cada una de las naves dispara diferentes poderes musicalmente y las misiones es para disfrutar...tan bueno como riukenden y contra",
    "Hola. Estoy buscando un juego seguramente de Playstation one. Trata de una batalla en el cual tu eres un robot y luchas contra una nave en distintos escenarios. Cada uno defiende un color, el rojo o el azul, y tiene una base en el extremo del escenario y desde cada base salen tanques y aviones de tu color que atacan a los del bando contrario. ganas cuando tus tropas en entran en su base. Ademas en el trayecto hay como ametralladoras que son neutras pero las puedes volver de tu bando y la nave también intenta quedárselas para el y asi atacan tus tropas cuando pasan por ahí",
    "Hola, oye como se llama un juego de exbox que esta en las maquinitas, es de unos personajes que tiene carros y se destruyen entre ellos, con lazer y otras cosas, lo mas relevante es un sientifico",
    "Hola!, Estoy buscando el nombre de un juego que me encantaba cuando era niña, era una saga de varios juegosde una mujer que era como militar y tenia misiones. Me acuerdo que en uno de los jjuegos ella estaba en un campamento militar y tenia que escapar escalando una cuerda y luego robar las llaves de una caminoneta y asi.... y otro era que tenia de escapar de unas casas indigenas en la selva, y si no me equivoco otro era que estaba en un camión secuestrada y tenia que romper el vidrío para poder encender la camioneta, se estrellara y escapar...! Para mí es muy importante encontrarlo, ayudaaaa :)",
    "Hola busco un juego desde hace tiempo, no recuerdo mucho como era, pero por lo poco que me acuerdo era que se tenia que empujar a soldados(creo) a agujeros para poder pasar de nivel, y muchas veces se tenia que llamar la atencion de ese soldado golpeando la pared para que se acercara al aggujero y poder empujarlo, tambien recuerdo que un nivel era de nieve y habian tres soldados, si uno ponia una vista especial se podia ver las huellas de estos hombres y saber quien era el culpable y empujarlo al agujero. El juego era para ps1",
    "hola, busco un juego q se trataba sobre un principe o un soldado que mataba momias creo que habian cofres, tambien entraba en una tienda para comprar unas botellas que eran colo rojo y azul y creo que cuando su potencia estaba lleno de color celeste botaba su poder a las momias y las quemaba algo asi porfa ayuda vengo como 3 años buscandola",
    "Vi un post antiguo de ti y de preguntas sore videojuegos y tengo una interesante que me persigue desde la infancia  (edad actual 20 años). Los juegos son extremadamente desconocidos y espero que me aclares mis dudas de cuales son por favor son aprox de la época de 1997 a 2004 época en donde los jugaba, uno se veia muy poligonal y el personaje parecia pelear contra unos tipos los cuales si les disparabas en los brazos se les cortaban y les salia liquido verde, el personaje tenia un traje negro y al iniciar el nivel debia caer de el cielo mientras disparaba algo. ademas tenia un brazo que parecia arma. si llegabas a morir en un nivel saltaba una calabera que se reia y aveces aparecia un item con cabeza de perro que soltaba bombas por el mapa en un avion, el segundo juego no era tan poligonal como el primero y el personaje parecia un viajero de el tiempo que en algunas partes viajaba en circuitos... estos juegos son extremadamente desconocidos nunca mas los volví a ver, me interesarían volver a jugarlos porque tengo flash backs de cuando los jugaba",
    "hola pasa que antes cuando joven jugaba en las maquinas arcade despues del colegio y jugaba un juego donde salia una navesita pequeña, que al romper una capsula con forma de huevo se hacia mas grandesita hasta formar un robat con escudo, aparecian letras para mejorarlo armas y esas cosas, la mejor era una como una chicharra que lansaba bolitas y detria todo, bueno espero me eyudes haber si lo encuentro para jugarlo otravez, gracias",
    "Hola. Entre los años 1989 1990 en las maquinistras, veía un arcade un juego donde un soldado aparecía en un sitio como prehistórico... la perspectiva del juego era aérea tipo shock troopers... inmediatamente salían unos dinosaurios enemmigos lo que recuerdo es que era bastante difícil el comienzo... esa máquina fue la primera que vi con ese tipo de palanca, ya que la empuñadura aparte de dirigir el personaje en diferentes direcciones, esta giraba completamente dándole al personaje la característica de mover o disparar su arma en cualquier dirección.....no tengo mas detalles ya que no me acuerdo mucho de ese juego ojala con los pocos datos que te di me puedas conseguir el nombre de ese juego. muchas gracias",
    "Estoy buscando un juego que era como un montón de tortuguitas, que caían de una 'caja' una por una. Había que darle a una alguna herramienta para desbloquear el camino y así hacer que todas llegaran a la 'meta' Por ejemplo: había picos, si se lo dabas a una esa iba y rompía por un rato",
    "hola, te voy a pedir varios juegos son juegos de internet. uno vos tenias una persona y le tenias que ir clavando una flecha para despues curarle la herida, en uno de los niveles había un vampiro entonces le tenias que pone runa cruz cortarle la cabeza, y después coser denuevo y ir tirando le cremitas en la quemaduras de la cruz y cosas asi. el siguiente vos sos una princesa arriba de un drago, y el boss del primer nivel hera una babosa voladora que ciando aparecía decia sorprice. y podias ir mejorando tu tiro y un tipo era mas util para matar golbos otro para matar bichos y asi, otro es uno que vos sos como una ciudad y te van atacando dragones y lanzarocas, y con el mouse como que dibujabas escudos también podías mejorar la ciudad y eso, otro era de como una bola peluda que enamorabas de otra bola peluda, y tenias un hijo que salia el adn de la tulla y de la otra y se juntaba uno y uno, e hibas haciendo tu propia dinastia de volitas kawaii peludas",
    "hola, mira podriais ayudarme, el juego que busco era en computador lo jugue hace unos cuantos años... Trataba de un personaje masculino casi adolecente, que en la primera pista comenzando aparece un esqueleto de dinosaurio y de la sombre del mismo salia como una especie de monstruo o algo asi, tocaba matarle con un arma que le daban solo por esa pista, despues tocaba seguir avanzando por cada pista evadiendo los monstruos o ingeniandosela para destruirles... El juego es genial muy entretenido, ayudenme por favor llevo tiempo buscandole pero no le e podido encontrar",
    "Hola, trato de encontrar un juego ya viejo. Era algo muy similar al wolfenstein, pero en este los enemigos eran caras grandes o payasos, y se escuchaba una risa cada que encontrabas a alguno de estos 'ji' 'ji' 'ji'. Yo lo juegue en PC, pero realmente no recuerdo si era de nintendo u otra consola. Los graficos eran mas o menos iguales al wolfwnstein duke nukem o doom y la jugabilidad mas o menos era la misma. Quiero pensar que se trataba de algun tipo de mod ya que no lo he encontrado",
    "Hola, Nunca pensé que escribiría en un blog de videojuegos porque apenas los he experimentado a lo largo de mi vida pero el otro día recordé un juego que estuvo en la pagina de juegos Ozu hace mucho tiempo y que me encantó.  Recuerdo escasas imágenes, se trataba de pasar niveles al estilo Mario Bros pero algo más cutre y el personaje era una tortuga o un dinosaurio. La temática del fondo cambiaba según el nivel de dificultad de los niveles: aéreo - un castillo... puede que alguien me sepa dar su nombre o una vía para que lo encuentre. Mil gracias.",
    "Hola disculpen, estoy buscando un juego q jugue en el playstation 2 q comenzaba en una selva tenias q pasar debajo de un arbol caido.... al pasar el arbol caido encontrabas una serpiente la cual podias matar y guardarla como comida... tambien cuando los enemigos se ponian en alerte les salia arriba de la cabeza un signo de admiracion... mas despues pasabas un puente colgadiso al pasarlo podias bajar en una cueva debajo del puente y ahi encontraba una AK-47. Si alguien dio mas o menos con ecplicacion por fas les pido su ayuda con el nombre del juego",
    "Hola a todos, no se si conocen un juego de rol que yo jugaba en windows 98 hace muchos años, era en tercera persona y empezaba en unas mazmorras enfrentando esqueletos. Si de algo sirve recuerdo que las posciones de vida eran verdes y otras eran azules no recuerdo para que eran. Lo quiero recordar por nostalgia",
    "busco un juego que son 2 personas un hombre y una mujer, el juego es rol y aventura, ellos lo que haces ir matando mounstros",
    "AYUDARME!!!!Hola!!, Llevo años buscando un juego de coches, se trataba de recoger con el coche distintos personajes y llevarlos a su destino sanos y salvos, por ejemplo: uno era un muñequito que pasabas cerca de su jaula y se colocaba automaticamente en la parte de atras del coche y seguiendo las indicaciones terminabas llevandolo como a un parque infantil. Otor era un robot y lo dejabas en una cabina de dj, era muy entretenido el juego la verdad. Recuerdo que en la tipica pegatina de los coches era una abeja y la marca del juego o algo asi tambien. Creo que su nombre era algo de bazz o buzz gracias. Se me habia olvidado el robot hacia un sonido como 'iansubiiiii' con un tonillo de voz muy gracioso y era para ordenador",
    "El juego que busco era de un chico/chica que tenia creo 5 o 6 mundos a los cuales entrar, el plano inicial era el muñeco en el espacio rodeado de estos mundos. Se podia entrar primero a cinco mundos pero no se podian matar a los jefes por el tipo de arma que se tenia, se tenia que conseguir una más poderosa, uno de los mundos era de agua no se podia uno sambillir en él porque se necesitaban unas zapatillas especiales, Entrando en uno de los mundos habia que recorrer un laberinto para encontrar al jefe de ese mundo, al entrar a pelear contra el jefe se entrar a un cuarto negro completamente el jefe era una especie de piedra cuadrado que nos perseguia y en ocasiones nos lanzaba algo si nos tocaba nos dañaba, Se contaban con algunas armas (Las unicas que recuerdo eran bomerangs y una especie de rayo que al lanzarse se espacia en forma de cruz), al derrotar al jefe se tenia cierto tiempo para salir del mundo porque explotaba si no saliamos nos moriamos con el mundo, asi era mundo por mundo, el juego terminaba al explotar el ultimo mundo la chica/chico quedaba en el espacio sin ningún mundo y se ponia THE END. Si alguien sabe como se llama el juego se lo voy a agradecer", 
    "Buenas noches, tengo como 1 mes intentado recordar el nombre de un juego de Barcos de Guerra antiguos dejare algunas descripciones a ver si alguien lo sabe, un juego de bargos de guerra a vela y con cañones! (fundamental), NO era de piratas! (fundamental), Era de batallas especificas es decir al comenzar seleccionabas de una lista de batallas famosas cual querias jugar (no recuerdo si de verdad era asi), Existian islas con construcciones pero en un detalle minimo MINIMO MINIMO! eran casi q cosas cuadradas el detalle mayor estaba en los barcos (fundamental), es muymuy viejo! quizas del 2003 no recuerdo. La verdad auunque parezcan carateristicas especificas nadie me ha podido ayudar! espero que en este foro logre alguien recordarlo!, Gracias!", 
    "ESTOY BUSCANDO UN JUEGO QUE LO JUGABA EN LA COMPUTADORA METIA UN DISCO QUE COMPRE Y VENIAN VARIOS JUEGOS Y UNO DE ELLOS ERA ESTE, MEDIO ME ACUERDO QUE SE LLAMABA WORLD OF ALGO ASI PERO YA LO BUSQUE Y LO BUSQUE Y NO LO ENCUENTRO... EL OBJETIVO ERA ENCONTRAR UNA LLAVE TENAS QUE IR ABRIENDO PUERTAS Y EN CADA PUERTA HABÍA VARIAS COSAS COMO JOYAS BALAS Y COMIDA YMETRALLETAS, Y TU HIBAS DISPARANDO YA QUE TAMBIEN HABIA TIPO POLICIAS QUE TENIAS QUE MATARLOS, Y SI SE TE ACABABAN LAS BALAS TENIAS UN CUCHILLO, AL ENCONTRAR LA LLAVE TE SALIA UN COMO ROBOT QUE TE PERSEGUUIA, Y TENIAS QUE ENCONTRAR LA PUERTA DEL ELEVADOR QUE ABRIAS CON LA LLAVE PARA PASAR DE NIVEL, MEDIO ME ACUERDO QUE EL PRIMER NIVEL LAS PUERTAS COMO PAREDES CREO ERAN VERDES O LAS PAREDES DE LADRILLOS Y PUERTAS VERDES, ALGO ASI ME URGE XFAVOR. MUCHAS GRACIAS",
    "Hola! busco un shooter de xbox 360 en primera persona, de entre el 2007-2008 de una especie de androide de armardura amarilla y cabeza alargada hacia atrás con un sólo ojo rojo, que tenia como arma cuerpo a cuerpo una katana, peleaba contra humanos junto a sus compañeros de su mismo 'modelo', en la misión que jugué salen de su base o de un transporte para repeler un contraataque o elimitar un puesto enemigo, el ambiente muestra un cielo rojizo medio nublado, en una ciuad destruida donde estan los supuestos rebeldes a la cual entras mediante su propia trinchera. La portada muestra al mismo robot con su katana parado sobre escombros, al rededor todo en grisis en las mismas condiciones",
    "Hola! estoy preguntando por el nombre de un juego de SNES, que comenzaba el personaje sumergido en el agua, perseguido por unos tentaculos despues de haber salido del pozo, te empezaba a perseguir un leon, luego que eres capturado por otros personajes y que despierrtas en una jaula colgalte al parecer en una mina, espero que haya dejado en claro el inicio del juego para saber el nombre. GRACIAS!"
];


const genButton = document.querySelector('.generate');
let inicio = "", introduccion ="", descripcion = "", cierre ="", fin = "";

function generateContent() {

    const randomTelefonitos = [];
    const postStart = [];
    const postIntroduction = [];
    const postDescription = [];
    const postClosing = [];
    const postEnd = [];

    //selecciona posts al azar, reemplaza puntos por comas para estandarizar el formato y los guarda en el arreglo de donde saldra el post final  
    for (let index = 0; index < 15; index++) {
        let randomvalue = Math.floor(Math.random() * posts.length);
        let randompost = posts[randomvalue].replace(/\./g, ',');
        randomTelefonitos.push(randompost);
    }
    //cada post, se va a dividir por comas
    randomTelefonitos.forEach(post => {
        let b = post.split(',');
        postStart.push(b.shift());
        if (b.length > 5) {
            postIntroduction.push(b.shift());
        }
        postEnd.push(b.pop());
        if (b.length > 5) {
            postClosing.push(b.pop());
        }
        postDescription.push(...b);
    });

    console.log(postStart); 
    console.log(postIntroduction); 
    console.log(postDescription); 
    console.log(postClosing);
    console.log(postEnd);

    formPhrase(postStart,postIntroduction,postDescription, postClosing, postEnd);
}

function formPhrase(start,introduction,description,closing, end) {
    inicio = start[Math.floor(Math.random() * start.length)]+',';

    introduccion = introduction[Math.floor(Math.random() * introduction.length)]+',';

    //descripcion toma tres frases distintas no vacias
    let descripcion1 = description[Math.floor(Math.random() * description.length)];
        while (descripcion1 === "") {
            descripcion1 = description[Math.floor(Math.random() * description.length)];
    }
    let descripcion2 = description[Math.floor(Math.random() * description.length)];
        while (descripcion2 === "" || (descripcion2 === descripcion1)) {
            descripcion2 = description[Math.floor(Math.random() * description.length)];
    }
    let descripcion3 = description[Math.floor(Math.random() * description.length)];
        while (descripcion3 === "" || (descripcion3 === descripcion1) || (descripcion3 === descripcion2)) {
            descripcion3 = description[Math.floor(Math.random() * description.length)];
    }

    descripcion = descripcion1 + ',' + descripcion2 + ',' + descripcion3;
    
    cierre = closing[Math.floor(Math.random() * closing.length)];

    //final de la frase
    fin = end[Math.floor(Math.random() * end.length)]
    while (fin === "") {
        fin = end[Math.floor(Math.random() * end.length)];
    }
    fin = '. ' + (fin.charAt(1).toUpperCase()) + (fin.substr(2));   
}

//contenido 
function insertText() {
    generateContent();
    document.getElementById('telefonito').innerHTML = inicio + introduccion + descripcion + cierre +  fin;
}

genButton.addEventListener('click', insertText);

